In [1]:
import torch
from torch import nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline


根据提供的notebook,Claude2对代码的建议和注释如下:

1. 数据处理部分可以添加更多注释,说明读取的数据字段含义,以及对数据的检查和处理思路。

2. 模型定义部分可以添加注释,说明输入和输出维度的设定依据,网络层数和神经元数量的选择依据等。

3. 训练评估部分的注释可以更详细,说明采用的数据分割方式,训练过程中的超参数,以及评估指标的计算方法。

4. 模型训练结果可以进行更深入的分析,检查是否存在过拟合或欠拟合,并结合业务目标提出后续优化思路。 

5. 可以添加模型效果可视化的代码,如Loss曲线,预测结果示例等,更直观地呈现模型效果。

6. 添加模型保存和加载的代码,便于训练后的模型重用。

7. 可以尝试不同模型结构或训练策略的比较实验。

8. 可以基于代码封装出函数或类,提高代码的复用性和模块化程度。

9. 添加类型注释,可以提高代码可读性和健壮性。

总体而言,该notebook内容完整,但仍有进一步提升注释、可视化、模块化、模型分析等方面的优化空间。

In [2]:
# 数据预处理
# df = pd.read_csv("../dataset/creditcard-tianchi.csv", index_col=None)
# del df['Time']
# df.head(3)
# df.head(30000).to_csv("../dataset/creditcard-3w.csv", index=False)  # 分拆数据到 creditcard-3w
# df.to_csv("../dataset/creditcard-all.csv", index=False)  # 分拆数据到 creditcard-3w

In [3]:
# 读取数据
df = pd.read_csv("../dataset/creditcard-all.csv", index_col=None)
df.head(3)


V1        V2        V3        V4        V5        V6        V7  \
0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   

         V8        V9       V10  ...       V21       V22       V23       V24  \
0  0.098698  0.363787  0.090794  ... -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425 -0.166974  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  0.207643  ...  0.247998  0.771679  0.909412 -0.689281   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  

[3 rows x 30 columns]

In [4]:
list1, list2, list3 = ['1','2'], ['a','b'], [5,6]

In [5]:
float(list1[0]) + 1

2.0

In [6]:
float(list3[0]) + 10

15.0

In [7]:
list1, list2, list3


(['1', '2'], ['a', 'b'], [5, 6])

In [8]:
list1 + list2 + list3

['1', '2', 'a', 'b', 5, 6]

In [9]:
# print( df.columns.to_list, [1,2])


In [10]:
# df.columns, df.columns.to_list 

In [11]:
df.Class.unique()

array([0, 1], dtype=int64)

In [12]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [13]:
# 列处理2
# df.groupby(['salary', 'sales']).size()

# pd.get_dummies(df.salary) # field内容编程列 list
# df = df.join( pd.get_dummies(df.salary) ) # 把列加入到 pandas fields
# del df['salary'] # 删除原来列

# pd.get_dummies(df.sales)  # 读日编码？？？
# df = df.rename(columns={'sales':'department'})  # 改列名
# df = df.join(pd.get_dummies(df.department))
# del df['department']
# df.head(3).to_csv("../dataset/test1.csv", index=False)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 30 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   V1      284807 non-null  float64
 1   V2      284807 non-null  float64
 2   V3      284807 non-null  float64
 3   V4      284807 non-null  float64
 4   V5      284807 non-null  float64
 5   V6      284807 non-null  float64
 6   V7      284807 non-null  float64
 7   V8      284807 non-null  float64
 8   V9      284807 non-null  float64
 9   V10     284807 non-null  float64
 10  V11     284807 non-null  float64
 11  V12     284807 non-null  float64
 12  V13     284807 non-null  float64
 13  V14     284807 non-null  float64
 14  V15     284807 non-null  float64
 15  V16     284807 non-null  float64
 16  V17     284807 non-null  float64
 17  V18     284807 non-null  float64
 18  V19     284807 non-null  float64
 19  V20     284807 non-null  float64
 20  V21     284807 non-null  float64
 21  V22     28

In [15]:
df.shape  # 行列

(284807, 30)

In [16]:
df.size # df的行x列， 共有多少数据cell

8544210

In [17]:
df.Class.unique()

array([0, 1], dtype=int64)

In [18]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [19]:
df.columns

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount', 'Class'],
      dtype='object')

In [20]:
# test1 = df.Class   # 输出的不是pd，只是列
# test2 = df.Class.values.reshape(-1,20)   # 从“列”格式转成了pd格式
# test2

In [21]:
Y_data = df.Class.values.reshape(-1,1)  # 转换成 pd type array
Y_data

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [22]:
# Y = torch.from_numpy(Y_data).type(torch.float32)  # 转换成tensor
Y = torch.from_numpy(Y_data).type(torch.FloatTensor)
Y.shape, Y.size(0) + 1

(torch.Size([284807, 1]), 284808)

In [23]:
X_columns = [c for c in df.columns if c != 'Class']
X_data = df[X_columns]  
# X = torch.from_numpy(X_data.values).type(torch.FloatTensor)
X = torch.from_numpy(X_data.values).type(torch.float32)
X.shape, X.size()

(torch.Size([284807, 29]), torch.Size([284807, 29]))

In [24]:
import torch.nn.functional as F  # 避免relu和sigmoid的初始化，可以直接调用
class Model(nn.Module):
    def __init__(self):
        super().__init__()      # 继承父类中所有的属性
        self.liner_1 = nn.Linear(29, 256)   # X.size(1)= 20； 定义64个后续中间层
        self.liner_2 = nn.Linear(256, 128)   # 接着，再定义64个后续中间层
        self.liner_3 = nn.Linear(128, 32)   # 接着，再定义64个后续中间层
        self.liner_4 = nn.Linear(32, 1)   # 接着，再定义64个后续中间层
    def forward(self, input):
        x = F.relu( self.liner_1(input) )
        x = F.relu( self.liner_2(x) )
        x = F.relu( self.liner_3(x) )
        x = F.sigmoid( self.liner_4(x) )
        return x

# 更加高级语言法，等价于Model
class Model_high(nn.Module):
    def __init__(self):
        super().__init__()      # 继承父类中所有的属性
        self.liner_1 = nn.Linear(29, 256)   # X.size(1)= 20； 定义64个后续中间层
        self.liner_2 = nn.Linear(256, 128)   # 接着，再定义64个后续中间层
        self.liner_3 = nn.Linear(128, 64)   # 接着，再定义64个后续中间层
        self.liner_4 = nn.Linear(64, 1)   # 接着，再定义64个后续中间层
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()
    def forward(self, input):
        x = self.Liner_1(input)
        x = self.relu(x)
        x = self.Liner_2(x)
        x = self.relu(x)
        x = self.Liner_3(x)
        x = self.sigmoid(x)
        return x

In [25]:
lr = 0.0001
def get_model():
    model = Model()
    opt = torch.optim.Adam(model.parameters(), lr=lr)
    return model, opt

In [26]:
model, optim = get_model()
print( model, "\n" )
print( optim )

Model(
  (liner_1): Linear(in_features=29, out_features=256, bias=True)
  (liner_2): Linear(in_features=256, out_features=128, bias=True)
  (liner_3): Linear(in_features=128, out_features=32, bias=True)
  (liner_4): Linear(in_features=32, out_features=1, bias=True)
) 

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.0001
    maximize: False
    weight_decay: 0
)


In [27]:
loss_fn = nn.BCELoss()
# batch = 64
# batch = 1024
# batch = 8192
# batch = 16384
batch = 32768
no_of_batches = len(X)//batch
epochs = 10
from torch.utils.data import TensorDataset, DataLoader


In [28]:
# Ver 4.1 - random_split Mode， charlie
# from torch.utils.data import random_split    
# def accuracy(y_pred, y_true):
#     y_pred = (y_pred > 0.5).type(torch.int32)
#     acc = (y_pred == y_true).float().mean()
#     return acc

# HR_dataset = TensorDataset(X, Y)
# test_ds, test_ds = random_split(HR_dataset, [0.8, 0.2]) 
# HR_dataloader = DataLoader(test_ds, batch_size=batch, shuffle=True)  # shuffle乱序取数
# epochMode = 41
# if epochMode == 41:  
#     for epoch in range( epochs ):
#         # for x,y in HR_dataloader:
#         for x,y in HR_dataloader:
#             y_pred = model(x)
#             loss = loss_fn(y_pred, y)
#             optim.zero_grad()
#             loss.backward()
#             optim.step()
#         with torch.no_grad():
#             print('epoch: ', epoch, ' loss: ', loss_fn(model(X), Y).data.item() )

In [29]:
# Ver 4.2 - sklearn mode
def accuracy(y_pred, y_true):
    y_pred = (y_pred > 0.5).type(torch.int32)
    acc = (y_pred == y_true).float().mean()
    return acc

from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(X_data, Y_data)
train_x.shape, test_x.shape, train_y.shape, test_y.shape

train_x = torch.from_numpy(train_x.values).type(torch.float32)
train_y = torch.from_numpy(train_y).type(torch.float32)
train_ds = TensorDataset(train_x, train_y)
train_dl = DataLoader(train_ds, batch_size=batch, shuffle=True)  # 需要shuffle，乱序执行

test_x = torch.from_numpy(test_x.values).type(torch.float32)
test_y = torch.from_numpy(test_y).type(torch.float32)
test_ds = TensorDataset(test_x, test_y)
test_dl = DataLoader(test_ds, batch_size=batch, shuffle=False)  # 不需要shuffle，减少运算量

MemoryError: Unable to allocate 15.8 MiB for an array with shape (29, 71202) and data type float64

计算正确率
- Sigmoid()是0和1之间的值， 大于0.5为1，否则是0
- out1 = (y-pred >0.5).type(torch.int32)  : 转换成0或1
- (out1 == labels).float().mean()

In [ ]:
%%time
epochs = 10
for epoch in range( epochs ):
    for x,y in train_dl:
        y_pred = model(x)
        loss = loss_fn(y_pred, y)
        optim.zero_grad()
        loss.backward()
        optim.step()
    with torch.no_grad():
        epoch_accuracy = accuracy(model(train_x), train_y)
        epoch_loss = loss_fn(model(train_x), train_y).data.item()
        epoch_test_accuracy = accuracy(model(test_x), test_y)
        epoch_test_loss = loss_fn(model(test_x), test_y).data.item()
        print('epoch: ', 
            epoch, ' train_loss: ', round(epoch_loss,4), ' Acc：', round(epoch_accuracy.item(),4),
            epoch, ' test_loss: ', round(epoch_test_loss,4), ' Acc：', round(epoch_test_accuracy.item(),4) )

epoch:  0  train_loss:  0.6165  Acc： 0.998 0  test_loss:  0.6167  Acc： 0.9978
epoch:  1  train_loss:  0.4733  Acc： 0.9983 1  test_loss:  0.4735  Acc： 0.9983
epoch:  2  train_loss:  0.4251  Acc： 0.9983 2  test_loss:  0.4251  Acc： 0.9983
epoch:  3  train_loss:  0.3914  Acc： 0.9983 3  test_loss:  0.3912  Acc： 0.9983
epoch:  4  train_loss:  0.3639  Acc： 0.9983 4  test_loss:  0.3636  Acc： 0.9983
epoch:  5  train_loss:  0.3382  Acc： 0.9983 5  test_loss:  0.3378  Acc： 0.9983
epoch:  6  train_loss:  0.314  Acc： 0.9983 6  test_loss:  0.3135  Acc： 0.9983
epoch:  7  train_loss:  0.2918  Acc： 0.9983 7  test_loss:  0.2913  Acc： 0.9983
epoch:  8  train_loss:  0.2706  Acc： 0.9983 8  test_loss:  0.27  Acc： 0.9983
epoch:  9  train_loss:  0.2493  Acc： 0.9983 9  test_loss:  0.2487  Acc： 0.9983
CPU times: total: 29.4 s
Wall time: 46.2 s


In [ ]:
# 最后一次计算结果：

epoch_accuracy = accuracy(model(train_x), train_y)
epoch_loss = loss_fn(model(train_x), train_y).data.item()
epoch_test_accuracy = accuracy(model(test_x), test_y)
epoch_test_loss = loss_fn(model(test_x), test_y).data.item()
print('epoch: ', 
    ' train_loss: ', round(epoch_loss,4), ' Acc：', round(epoch_accuracy.item(),4),
    ' test_loss: ', round(epoch_test_loss,4), ' Acc：', round(epoch_test_accuracy.item(),4) )

epoch:   train_loss:  0.2493  Acc： 0.9983  test_loss:  0.2487  Acc： 0.9983


In [ ]:
# print( loss_fn(model(train_x), train_y).data.item() )
# accuracyRate = ((model(train_x).data.numpy()).astype('int') == train_y.numpy().astype('int')).mean()
# print("训练数据 - 准确率%：", accuracyRate*100) 

# print( loss_fn(model(test_x), test_y).data.item() )
# accuracyRate = ((model(test_x).data.numpy()).astype('int') == test_y.numpy().astype('int')).mean()
# print("测试数据 - 准确率%：", accuracyRate*100) 

数据准确性验证
过拟合/欠拟合
- 过拟合：对于已知数据过度拟合，对未知数据预测性差
- 欠拟合：对于已知数据拟合不够，对未知数据预测性差
  
tensor合并
- 

In [ ]:
train_x.shape, train_y.shape

(torch.Size([213605, 29]), torch.Size([213605, 1]))

In [ ]:
train_cat = torch.cat([train_x, train_y],dim=1)   # 沿着Dimension 1进行合并

In [ ]:
train_cat.shape

torch.Size([213605, 30])

In [ ]:
# train_all.numpy()
np.savetxt('../dataset/test20.csv', train_cat.numpy(),fmt='%.8f',delimiter=',') # 直接覆盖

In [ ]:
train_np = np.loadtxt('../dataset/test20.csv', dtype = np.float32, delimiter=',')

In [ ]:
train_np.shape, train_np

((213605, 30),
 array([[ 2.0088439e+00, -3.5165665e-01, -2.1254924e-01, ...,
         -4.0231138e-02,  3.0000001e-01,  0.0000000e+00],
        [ 1.2169847e+00, -7.5984633e-01,  3.3216605e-01, ...,
          3.3281001e-04,  3.9950001e+01,  0.0000000e+00],
        [-3.1524095e-01,  9.9165106e-01, -1.0809172e-01, ...,
          3.1399969e-02,  9.9899998e+00,  0.0000000e+00],
        ...,
        [ 1.2388279e+00,  9.4449177e-02,  9.4030842e-02, ...,
         -5.6002699e-03,  1.6940001e+01,  0.0000000e+00],
        [-1.6124758e+00,  6.9228512e-01,  1.8747337e+00, ...,
         -2.7487901e-01,  2.8969999e+01,  0.0000000e+00],
        [ 8.3063328e-01, -1.1565137e+00,  6.0491246e-01, ...,
          7.0290759e-02,  2.3200000e+02,  0.0000000e+00]], dtype=float32))