In [4]:
import torch
from torch import nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


张量的创建、和np的转换

In [ ]:
# 创建 tensor， 定义类型 
x1 = torch.rand(2, 3)       # 0-1之间的随机数
x2 = torch.randn(3, 4)      # 动态分布随机数
x3 = torch.zeros(2, 3)
x4 = torch.ones((2, 3, 4), dtype=torch.int64)   # 定义1数据的类型，预设是float
print(x3) 
print(x4)

# 显示tensor信息
print(x4.size())       
print(x4.shape)        # 类似size(), 但没有（）
x4.size(1)
x4.size(2)

In [ ]:
# 转换 list 到tensor; 定义和更改数据类型
x = torch.tensor([6.1, 2])                          # 转换list，类型不变
print(x)
x = torch.tensor([6, 2], dtype=torch.float32)       # 制定转换成 float32类型
print(x)

print(x.type)
print(x.type( torch.int64 ))                        # tensor再转换到int64

print()

In [ ]:
# np类型、tensor类型之间的转换 
x1np = np.random.randn(2, 3)        # np创建一个 array, 随机分布
print(x1np)
x1 = torch.from_numpy( x1np )       # np 转换到 tensor
print(x1)
print(x1.numpy())                   # tensor再转回到np

张量运算：相加、相减

In [ ]:
## 张量运算：相加、相减; 
print(x1)
x2 = torch.rand(2,3)
print(x2)
x = x1 + x2
print(x)
print(x1 + 3)


In [ ]:
# 相加后是否赋值x1
print(x1.add(x2))       # x1，不改变x1
print(x1.add_(-x2))      # x1改变了


In [ ]:
# 变形
print( x1.view(3,2) )
# -1 ... 用法
print( x1.view(-1, 1))      # n行，1列
print( x1.view(1, -1))      # 
print( x1.view(2, -1))      # 

In [ ]:
# 平均、求和、最大、最小
print(x1.mean())
print(x1.sum())
print(x1.max())
print(x1.min())

In [ ]:
print(x1.min().item() + 1)      # 单一的tensor变成数值

张量的自动微分
- requires_grad = True, 则在完成计算后，可以调用 .backword()并自动计算所有梯度。
- tensor3个属性：data，grad，grad_fn
  -  x = torch.ones(2,2, requires_grad=True)
  -  x.data ，x的内容
  -  x.grad , x的梯度
- 改变
  - 

In [6]:
x = torch.ones(2,2, requires_grad=True)     # True 表示开始跟踪x的变化，计算梯度
print(x.requires_grad)

True


In [10]:
print(x.data)
print(x.grad)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
None
None


In [13]:
y = x + 2
print(y.data)
print(y.requires_grad)  # x 的 grad属性传递到了 y
print(y.grad)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]])
True
None


d:\temp\ipykernel_17784\1379503892.py:4: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:491.)
  print(y.grad)


In [16]:
z = y*y + 3
print(z.data)
print(z.requires_grad)  # x 的 grad属性传递到了 y
print(z.grad)
print(z.grad_fn)

tensor([[12., 12.],
        [12., 12.]])
True
None


d:\temp\ipykernel_17784\1776470700.py:4: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:491.)
  print(z.grad)
